name: Karma and Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  karma-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:prod

  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start mockapi
        run: | 
          npm ci
          npm run start:mockapi

      - name: Start Cypress tests
        run: | 
          npm ci
          npm run cypress:e2e